# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
r: bioc-devel
r_build_args: --keep-empty-dirs --no-resave-data --no-build-vignettes
r_check_args: --no-vignettes --timings

after_success:
  - Rscript -e 'BiocCheck::BiocCheck(".")'
